/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pvs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pkerleo
 */
public class Main extends javax.swing.JFrame {
    
    Connection meineConne = null;

    /**
     * Creates new form Home
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        new TextPrompt("Username", usernameTextField);
        new TextPrompt("Passwort", userPasswordField);
        try {
            meineConne = DriverManager.getConnection("jdbc:mysql://localhost:3306/ritoemed", "root", "root");
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        loginInstructionLabel = new javax.swing.JLabel();
        userInputPanel = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JFormattedTextField();
        userPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Herzlich Willkomen auf der RITOEMED Plattform!");
        welcomeLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(welcomeLabel, java.awt.BorderLayout.PAGE_START);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, java.awt.BorderLayout.PAGE_END);

        loginPanel.setLayout(new java.awt.BorderLayout());

        loginInstructionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginInstructionLabel.setText("Bitte geben Sie Ihren Usernamen und Ihr Passwort ein!");
        loginPanel.add(loginInstructionLabel, java.awt.BorderLayout.PAGE_START);

        userInputPanel.setLayout(new javax.swing.BoxLayout(userInputPanel, javax.swing.BoxLayout.Y_AXIS));

        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        userInputPanel.add(usernameTextField);

        userPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userInputPanel.add(userPasswordField);

        loginPanel.add(userInputPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(loginPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        ResultSet rs = null;
        try {
            pvs.user.Password sa = new pvs.user.Password();
            String loginSQL = "select password from user where username = ?";
            PreparedStatement getPasswordStatement = meineConne.prepareStatement(loginSQL);
            getPasswordStatement.setString(1, usernameTextField.getText());
            rs = getPasswordStatement.executeQuery();
            boolean existingUser = rs.next();
            System.out.println(sa.hashPassword("marc"));
            System.out.println(sa.hashPassword("marc"));
            if (existingUser == true) {
                ResultSetMetaData rsmd = rs.getMetaData();
                System.out.println(rs.getString("password"));
                if (sa.checkPassword(userPasswordField.getText(), rs.getString("password")) == true) {
//                System.out.println("yeha");
                    OperationFrame operationFrame = new OperationFrame(this);
                    operationFrame.setVisible(true);
                    this.setVisible(false);
                    userPasswordField.setText("");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Das Passwort stimmt nicht!",
                            "Login fehlgeschlagen", JOptionPane.ERROR_MESSAGE);
                    userPasswordField.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Der Username " + usernameTextField.getText()
                        + " existiert nicht!",
                        "Login fehlgeschlagen", JOptionPane.ERROR_MESSAGE);
                userPasswordField.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginInstructionLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel userInputPanel;
    private javax.swing.JPasswordField userPasswordField;
    private javax.swing.JFormattedTextField usernameTextField;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
